package aurora.plugin.excelreport;

import org.apache.poi.ss.usermodel.CellStyle;

public enum IndexedCellStyle {	
	//水平
	ALIGN_GENERAL(CellStyle.ALIGN_GENERAL),//常规
	ALIGN_LEFT(CellStyle.ALIGN_LEFT),//靠左（缩进）style.setIndention 设置缩进量
	ALIGN_CENTER(CellStyle.ALIGN_CENTER),//居中
	ALIGN_RIGHT(CellStyle.ALIGN_RIGHT),//右
	ALIGN_FILL(CellStyle.ALIGN_FILL),//填充
	ALIGN_JUSTIFY(CellStyle.ALIGN_JUSTIFY),//两端对齐
	ALIGN_CENTER_SELECTION(CellStyle.ALIGN_CENTER_SELECTION),//跨列居中
	//垂直
	VERTICAL_TOP(CellStyle.VERTICAL_TOP),//顶端
	VERTICAL_CENTER(CellStyle.VERTICAL_CENTER),//居中
	VERTICAL_BOTTOM(CellStyle.VERTICAL_BOTTOM),//底端
	VERTICAL_JUSTIFY(CellStyle.VERTICAL_JUSTIFY),//两段对齐
	
	BORDER_NONE(CellStyle.BORDER_NONE),
	BORDER_THIN(CellStyle.BORDER_THIN),
	BORDER_MEDIUM(CellStyle.BORDER_MEDIUM),
	BORDER_DASHED(CellStyle.BORDER_DASHED),
	BORDER_HAIR(CellStyle.BORDER_HAIR),
	BORDER_THICK(CellStyle.BORDER_THICK),
	BORDER_DOUBLE(CellStyle.BORDER_DOUBLE),
	BORDER_DOTTED(CellStyle.BORDER_DOTTED),
	BORDER_MEDIUM_DASHED(CellStyle.BORDER_MEDIUM_DASHED),
	BORDER_DASH_DOT(CellStyle.BORDER_DASH_DOT),
	BORDER_MEDIUM_DASH_DOT(CellStyle.BORDER_MEDIUM_DASH_DOT),
	BORDER_DASH_DOT_DOT(CellStyle.BORDER_DASH_DOT_DOT),
	BORDER_MEDIUM_DASH_DOT_DOT(CellStyle.BORDER_MEDIUM_DASH_DOT_DOT),
	BORDER_SLANTED_DASH_DOT(CellStyle.BORDER_SLANTED_DASH_DOT),
	
	NO_FILL(CellStyle.NO_FILL),
	SOLID_FOREGROUND(CellStyle.SOLID_FOREGROUND),
	FINE_DOTS(CellStyle.FINE_DOTS),
	ALT_BARS(CellStyle.ALT_BARS),
	SPARSE_DOTS(CellStyle.SPARSE_DOTS),
	THICK_HORZ_BANDS(CellStyle.THICK_HORZ_BANDS),
	THICK_VERT_BANDS(CellStyle.THICK_VERT_BANDS),
	THICK_BACKWARD_DIAG(CellStyle.THICK_BACKWARD_DIAG),
	THICK_FORWARD_DIAG(CellStyle.THICK_FORWARD_DIAG),	
	BIG_SPOTS(CellStyle.BIG_SPOTS),
	BRICKS(CellStyle.BRICKS),
	THIN_HORZ_BANDS(CellStyle.THIN_HORZ_BANDS),
	THIN_VERT_BANDS(CellStyle.THIN_VERT_BANDS),
	THIN_BACKWARD_DIAG(CellStyle.THIN_BACKWARD_DIAG),
	THIN_FORWARD_DIAG(CellStyle.THIN_FORWARD_DIAG),
	SQUARES(CellStyle.SQUARES),
	DIAMONDS(CellStyle.DIAMONDS),
	LESS_DOTS(CellStyle.LESS_DOTS),	
	LEAST_DOTS(CellStyle.LEAST_DOTS);
	public final short index;

	private IndexedCellStyle(int idx) {
		this.index = (short) idx;
	}

	public short getIndex() {
		return this.index;
	}

}
