<procedure xmlns="uncertain.proc">
	<fields>
		<field name="SqlStatementType" type="String" usage="input" />	
		<field name="BusinessModel" usage="input"/>
		<field name="SqlStatement"  />
		<field name="SqlString"  />
	</fields>
	<switch test="@SqlGenerationMode" name="switch">
		<case value="AutoGenerate" name="AutoGenerate">
			<action name="Create${@SqlStatementType}Statement" input="BusinessModel" output="SqlStatement"/>
			<action name="Populate${@SqlStatementType}Statement" input="SqlStatement,BusinessModel"/>
			<action name="Create${@SqlStatementType}Sql" input="SqlStatement,BusinessModel" output="SqlString" />
			<action name="Test1" />
		</case>
		<case value="Predefined">
			<action name="CreateOperationSql" input="BusinessModel" output="SqlString" />
			<action name="PopulateOperationSql" input="SqlString" />
		</case>
	</switch>
</procedure>