<?xml version="1.0" encoding="UTF-8"?>
<procedure xmlns="uncertain.proc" returnField="Sql">
	<fields>
		<field name="Table" type="uncertain.testcase.dbsample.Table" path="source/@table" description="Table object to define schema" usage="input"/>
		<field name="Fields" type="StringBuffer" path="/temp/@fields"/>
		<field name="Entity" type="java.lang.StringBuffer"/>
		<field name="WhereClause" type="StringBuffer"/>
		<field name="Sql" type="String" usage="return"/>
		<field name="Hints" type="StringBuffer" />
	</fields>
	<action name="test"/>	
	<action name="GetEntity" input="Table" output="Entity"/>
	<action name="CreateSqlFields" output="Fields"/>
	<action name="CreateWhereClause" output="WhereClause"/>
	<action name="CreateSql" input="Fields, Entity , WhereClause" output="Sql, Hints"/>
</procedure>
