<?xml version="1.0" encoding="utf-8" ?>
<procedure xmlns="uncertain.proc">
	<action Name="InitParams" />
	<action Name="RaiseException" />
	<action Name="UnExpectedAction" />
	<action Name="DoRight" />
	<exception-handles>
		<catch Exception="java.io.IOException" Destination="@result" NextStep="DoRight"/>
		<catch Exception="java.lang.IllegalStateException" NextStep="DoRight">
			<set Field="@set1" Value="true" />
			<set Field="@set2" Value="true" />
		</catch>
		<catch Exception="java.sql.SQLException">
			<!-- throw exception again -->
			<action Name="SQLException" />
		</catch>
		<!--
		<catch Exception="*">
			<action Name="AnyException" />
		</catch>	
		-->
	</exception-handles>
</procedure>