<?xml version="1.0" encoding="utf-8" ?>
<procedure xmlns="uncertain.proc">
	<assert field="/test/@null" operator="null" />
	<assert field="/test/@notnull" operator="not null" />
	<assert field="/test/@eq" operator="==" value="hello" />
	<assert field="/test/@neq" operator="!=" value="hello" />
	<assert field="/test/@gt" operator="&gt;" value="1.2" />
	<assert field="/test/@lt" operator="&lt;" value="${/test/@number}" />				
	<assert field="/test/@goe" operator="&gt;=" value="0" />				
	<assert field="/test/@loe" operator="&lt;=" value="0" />
		
</procedure>