<?xml version="1.0" encoding="utf-8" ?>
<p:procedure xmlns:p="uncertain.proc" debug="true">
	<p:action Name="InitParams" />
	<p:action Name="RaiseException" />
	<p:action Name="UnExpectedAction" />
	<p:action Name="DoRight" />
	<exception-handles>
		<p:catch Exception="java.io.IOException" Destination="@result" NextStep="DoRight"/>
		<p:catch Exception="*">
			<p:action Name="AnyException" />
		</p:catch>	
	</exception-handles>
</p:procedure>