CREATE TABLE `bpmn_recipient_rules` (
  `rule_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `rule_code` varchar(30) NOT NULL DEFAULT '' COMMENT '规则CODE',
  `rule_type` varchar(30) NOT NULL COMMENT '审批规则类型',
  `name_id` bigint(20) DEFAULT NULL COMMENT '审批规则名称',
  `description_id` bigint(20) DEFAULT NULL COMMENT '描述ID',
  `procedure_name` varchar(200) DEFAULT NULL COMMENT '执行过程',
  `sys_flag` varchar(1) DEFAULT NULL COMMENT '系统创建标志',
  `parameter_1_type` varchar(30) DEFAULT NULL COMMENT 'SELECT：LOV；INPUT：textedit',
  `parameter_1_desc` varchar(1000) DEFAULT NULL COMMENT '参数1描述',
  `parameter_1_url` varchar(1000) DEFAULT NULL COMMENT 'Lov组件文件名',
  `parameter_2_type` varchar(30) DEFAULT NULL COMMENT 'SELECT：LOV；INPUT：textedit',
  `parameter_2_desc` varchar(1000) DEFAULT NULL COMMENT '参数2描述',
  `parameter_2_url` varchar(1000) DEFAULT NULL COMMENT 'Lov组件文件名',
  `parameter_3_type` varchar(30) DEFAULT NULL COMMENT 'SELECT：LOV；INPUT：textedit',
  `parameter_3_desc` varchar(1000) DEFAULT NULL COMMENT '参数3描述',
  `parameter_3_url` varchar(1000) DEFAULT NULL COMMENT 'Lov组件文件名',
  `parameter_4_type` varchar(30) DEFAULT NULL COMMENT 'SELECT：LOV；INPUT：textedit',
  `parameter_4_desc` varchar(1000) DEFAULT NULL COMMENT '参数4描述',
  `parameter_4_url` varchar(1000) DEFAULT NULL COMMENT 'Lov组件文件名',
  `created_by` decimal(10,0) DEFAULT NULL COMMENT '创建用户ID',
  `creation_date` datetime DEFAULT NULL COMMENT '创建日期',
  `last_updated_by` decimal(10,0) DEFAULT NULL COMMENT '最后更新用户ID',
  `last_update_date` datetime DEFAULT NULL COMMENT '最后更新日期',
  PRIMARY KEY (`rule_id`),
  UNIQUE KEY `bpmn_recipient_rules_u1` (`rule_code`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COMMENT='审批规则定义表';
