
package com.microsoft.schemas.sharepoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ListsSoap", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListsSoap {


    /**
     * 
     * @param listName
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListResponse.GetListResult
     */
    @WebMethod(operationName = "GetList", action = "http://schemas.microsoft.com/sharepoint/soap/GetList")
    @WebResult(name = "GetListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListResponse")
    public com.microsoft.schemas.sharepoint.GetListResponse.GetListResult getList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param listName
     * @param viewName
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListAndViewResponse.GetListAndViewResult
     */
    @WebMethod(operationName = "GetListAndView", action = "http://schemas.microsoft.com/sharepoint/soap/GetListAndView")
    @WebResult(name = "GetListAndViewResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListAndView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListAndView")
    @ResponseWrapper(localName = "GetListAndViewResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListAndViewResponse")
    public com.microsoft.schemas.sharepoint.GetListAndViewResponse.GetListAndViewResult getListAndView(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName);

    /**
     * 
     * @param listName
     */
    @WebMethod(operationName = "DeleteList", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteList")
    @RequestWrapper(localName = "DeleteList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteList")
    @ResponseWrapper(localName = "DeleteListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteListResponse")
    public void deleteList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

    /**
     * 
     * @param templateID
     * @param listName
     * @param description
     * @return
     *     returns com.microsoft.sharepoint.webservices.AddListResponse.AddListResult
     */
    @WebMethod(operationName = "AddList", action = "http://schemas.microsoft.com/sharepoint/soap/AddList")
    @WebResult(name = "AddListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddList")
    @ResponseWrapper(localName = "AddListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddListResponse")
    public com.microsoft.schemas.sharepoint.AddListResponse.AddListResult addList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String description,
        @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int templateID);

    /**
     * 
     * @param templateID
     * @param listName
     * @param description
     * @param featureID
     * @return
     *     returns com.microsoft.sharepoint.webservices.AddListFromFeatureResponse.AddListFromFeatureResult
     */
    @WebMethod(operationName = "AddListFromFeature", action = "http://schemas.microsoft.com/sharepoint/soap/AddListFromFeature")
    @WebResult(name = "AddListFromFeatureResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddListFromFeature", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddListFromFeature")
    @ResponseWrapper(localName = "AddListFromFeatureResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddListFromFeatureResponse")
    public com.microsoft.schemas.sharepoint.AddListFromFeatureResponse.AddListFromFeatureResult addListFromFeature(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String description,
        @WebParam(name = "featureID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String featureID,
        @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        int templateID);

    /**
     * 
     * @param listName
     * @param deleteFields
     * @param listProperties
     * @param updateFields
     * @param listVersion
     * @param newFields
     * @return
     *     returns com.microsoft.sharepoint.webservices.UpdateListResponse.UpdateListResult
     */
    @WebMethod(operationName = "UpdateList", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateList")
    @WebResult(name = "UpdateListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateList")
    @ResponseWrapper(localName = "UpdateListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateListResponse")
    public com.microsoft.schemas.sharepoint.UpdateListResponse.UpdateListResult updateList(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateList.ListProperties listProperties,
        @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateList.NewFields newFields,
        @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateList.UpdateFields updateFields,
        @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateList.DeleteFields deleteFields,
        @WebParam(name = "listVersion", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listVersion);

    /**
     * 
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListCollectionResponse.GetListCollectionResult
     */
    @WebMethod(operationName = "GetListCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetListCollection")
    @WebResult(name = "GetListCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListCollection")
    @ResponseWrapper(localName = "GetListCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListCollectionResponse")
    public com.microsoft.schemas.sharepoint.GetListCollectionResponse.GetListCollectionResult getListCollection();

    /**
     * 
     * @param listName
     * @param viewName
     * @param queryOptions
     * @param webID
     * @param query
     * @param viewFields
     * @param rowLimit
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListItemsResponse.GetListItemsResult
     */
    @WebMethod(operationName = "GetListItems", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItems")
    @WebResult(name = "GetListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListItemsResponse")
    public com.microsoft.schemas.sharepoint.GetListItemsResponse.GetListItemsResult getListItems(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItems.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItems.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItems.QueryOptions queryOptions,
        @WebParam(name = "webID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webID);

    /**
     * 
     * @param listName
     * @param viewFields
     * @param contains
     * @param since
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListItemChangesResponse.GetListItemChangesResult
     */
    @WebMethod(operationName = "GetListItemChanges", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChanges")
    @WebResult(name = "GetListItemChangesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChanges", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListItemChanges")
    @ResponseWrapper(localName = "GetListItemChangesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListItemChangesResponse")
    public com.microsoft.schemas.sharepoint.GetListItemChangesResponse.GetListItemChangesResult getListItemChanges(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItemChanges.ViewFields viewFields,
        @WebParam(name = "since", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String since,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItemChanges.Contains contains);

    /**
     * 
     * @param listName
     * @param viewName
     * @param queryOptions
     * @param changeToken
     * @param query
     * @param viewFields
     * @param contains
     * @param rowLimit
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult
     */
    @WebMethod(operationName = "GetListItemChangesSinceToken", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChangesSinceToken")
    @WebResult(name = "GetListItemChangesSinceTokenResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListItemChangesSinceToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListItemChangesSinceToken")
    @ResponseWrapper(localName = "GetListItemChangesSinceTokenResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListItemChangesSinceTokenResponse")
    public com.microsoft.schemas.sharepoint.GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult getListItemChangesSinceToken(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String viewName,
        @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItemChangesSinceToken.Query query,
        @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItemChangesSinceToken.ViewFields viewFields,
        @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String rowLimit,
        @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItemChangesSinceToken.QueryOptions queryOptions,
        @WebParam(name = "changeToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String changeToken,
        @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.GetListItemChangesSinceToken.Contains contains);

    /**
     * 
     * @param listName
     * @param updates
     * @return
     *     returns com.microsoft.sharepoint.webservices.UpdateListItemsResponse.UpdateListItemsResult
     */
    @WebMethod(operationName = "UpdateListItems", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateListItems")
    @WebResult(name = "UpdateListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateListItems")
    @ResponseWrapper(localName = "UpdateListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateListItemsResponse")
    public com.microsoft.schemas.sharepoint.UpdateListItemsResponse.UpdateListItemsResult updateListItems(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "updates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateListItems.Updates updates);

    /**
     * 
     * @param message
     * @param listName
     * @return
     *     returns com.microsoft.sharepoint.webservices.AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult
     */
    @WebMethod(operationName = "AddDiscussionBoardItem", action = "http://schemas.microsoft.com/sharepoint/soap/AddDiscussionBoardItem")
    @WebResult(name = "AddDiscussionBoardItemResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddDiscussionBoardItem", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddDiscussionBoardItem")
    @ResponseWrapper(localName = "AddDiscussionBoardItemResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddDiscussionBoardItemResponse")
    public com.microsoft.schemas.sharepoint.AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult addDiscussionBoardItem(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "message", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        byte[] message);

    /**
     * 
     * @param strFieldName
     * @param strlistItemID
     * @param strlistID
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetVersionCollectionResponse.GetVersionCollectionResult
     */
    @WebMethod(operationName = "GetVersionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetVersionCollection")
    @WebResult(name = "GetVersionCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetVersionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetVersionCollection")
    @ResponseWrapper(localName = "GetVersionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetVersionCollectionResponse")
    public com.microsoft.schemas.sharepoint.GetVersionCollectionResponse.GetVersionCollectionResult getVersionCollection(
        @WebParam(name = "strlistID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strlistID,
        @WebParam(name = "strlistItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strlistItemID,
        @WebParam(name = "strFieldName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String strFieldName);

    /**
     * 
     * @param listName
     * @param listItemID
     * @param fileName
     * @param attachment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/AddAttachment")
    @WebResult(name = "AddAttachmentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "AddAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddAttachment")
    @ResponseWrapper(localName = "AddAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.AddAttachmentResponse")
    public String addAttachment(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID,
        @WebParam(name = "fileName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String fileName,
        @WebParam(name = "attachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        byte[] attachment);

    /**
     * 
     * @param listName
     * @param listItemID
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetAttachmentCollectionResponse.GetAttachmentCollectionResult
     */
    @WebMethod(operationName = "GetAttachmentCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetAttachmentCollection")
    @WebResult(name = "GetAttachmentCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetAttachmentCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetAttachmentCollection")
    @ResponseWrapper(localName = "GetAttachmentCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetAttachmentCollectionResponse")
    public com.microsoft.schemas.sharepoint.GetAttachmentCollectionResponse.GetAttachmentCollectionResult getAttachmentCollection(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID);

    /**
     * 
     * @param listName
     * @param listItemID
     * @param url
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteAttachment")
    @RequestWrapper(localName = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteAttachment")
    @ResponseWrapper(localName = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteAttachmentResponse")
    public void deleteAttachment(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listItemID,
        @WebParam(name = "url", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String url);

    /**
     * 
     * @param pageUrl
     * @param lastmodified
     * @param checkoutToLocal
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckOutFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckOutFile")
    @WebResult(name = "CheckOutFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CheckOutFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.CheckOutFile")
    @ResponseWrapper(localName = "CheckOutFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.CheckOutFileResponse")
    public boolean checkOutFile(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl,
        @WebParam(name = "checkoutToLocal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String checkoutToLocal,
        @WebParam(name = "lastmodified", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String lastmodified);

    /**
     * 
     * @param pageUrl
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UndoCheckOut", action = "http://schemas.microsoft.com/sharepoint/soap/UndoCheckOut")
    @WebResult(name = "UndoCheckOutResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UndoCheckOut", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UndoCheckOut")
    @ResponseWrapper(localName = "UndoCheckOutResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UndoCheckOutResponse")
    public boolean undoCheckOut(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl);

    /**
     * 
     * @param checkinType
     * @param pageUrl
     * @param comment
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckInFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckInFile")
    @WebResult(name = "CheckInFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CheckInFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.CheckInFile")
    @ResponseWrapper(localName = "CheckInFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.CheckInFileResponse")
    public boolean checkInFile(
        @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String pageUrl,
        @WebParam(name = "comment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String comment,
        @WebParam(name = "CheckinType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String checkinType);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListContentTypesResponse.GetListContentTypesResult
     */
    @WebMethod(operationName = "GetListContentTypes", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentTypes")
    @WebResult(name = "GetListContentTypesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentTypes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListContentTypes")
    @ResponseWrapper(localName = "GetListContentTypesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListContentTypesResponse")
    public com.microsoft.schemas.sharepoint.GetListContentTypesResponse.GetListContentTypesResult getListContentTypes(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @return
     *     returns com.microsoft.sharepoint.webservices.GetListContentTypeResponse.GetListContentTypeResult
     */
    @WebMethod(operationName = "GetListContentType", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentType")
    @WebResult(name = "GetListContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "GetListContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListContentType")
    @ResponseWrapper(localName = "GetListContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.GetListContentTypeResponse")
    public com.microsoft.schemas.sharepoint.GetListContentTypeResponse.GetListContentTypeResult getListContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param listName
     * @param contentTypeProperties
     * @param addToView
     * @param displayName
     * @param parentType
     * @param fields
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/CreateContentType")
    @WebResult(name = "CreateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "CreateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.CreateContentType")
    @ResponseWrapper(localName = "CreateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.CreateContentTypeResponse")
    public String createContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "displayName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String displayName,
        @WebParam(name = "parentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String parentType,
        @WebParam(name = "fields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.CreateContentType.Fields fields,
        @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.CreateContentType.ContentTypeProperties contentTypeProperties,
        @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String addToView);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @param contentTypeProperties
     * @param deleteFields
     * @param updateFields
     * @param addToView
     * @param newFields
     * @return
     *     returns com.microsoft.sharepoint.webservices.UpdateContentTypeResponse.UpdateContentTypeResult
     */
    @WebMethod(operationName = "UpdateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentType")
    @WebResult(name = "UpdateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateContentType")
    @ResponseWrapper(localName = "UpdateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateContentTypeResponse")
    public com.microsoft.schemas.sharepoint.UpdateContentTypeResponse.UpdateContentTypeResult updateContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateContentType.ContentTypeProperties contentTypeProperties,
        @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateContentType.NewFields newFields,
        @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateContentType.UpdateFields updateFields,
        @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateContentType.DeleteFields deleteFields,
        @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String addToView);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @return
     *     returns com.microsoft.sharepoint.webservices.DeleteContentTypeResponse.DeleteContentTypeResult
     */
    @WebMethod(operationName = "DeleteContentType", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentType")
    @WebResult(name = "DeleteContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "DeleteContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteContentType")
    @ResponseWrapper(localName = "DeleteContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteContentTypeResponse")
    public com.microsoft.schemas.sharepoint.DeleteContentTypeResponse.DeleteContentTypeResult deleteContentType(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId);

    /**
     * 
     * @param newDocument
     * @param listName
     * @param contentTypeId
     * @return
     *     returns com.microsoft.sharepoint.webservices.UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult
     */
    @WebMethod(operationName = "UpdateContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument")
    @WebResult(name = "UpdateContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateContentTypeXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateContentTypeXmlDocumentResponse")
    public com.microsoft.schemas.sharepoint.UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult updateContentTypeXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateContentTypeXmlDocument.NewDocument newDocument);

    /**
     * 
     * @param newDocument
     * @param listName
     * @return
     *     returns com.microsoft.sharepoint.webservices.UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult
     */
    @WebMethod(operationName = "UpdateContentTypesXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypesXmlDocument")
    @WebResult(name = "UpdateContentTypesXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "UpdateContentTypesXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateContentTypesXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypesXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.UpdateContentTypesXmlDocumentResponse")
    public com.microsoft.schemas.sharepoint.UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult updateContentTypesXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        com.microsoft.schemas.sharepoint.UpdateContentTypesXmlDocument.NewDocument newDocument);

    /**
     * 
     * @param listName
     * @param contentTypeId
     * @param documentUri
     * @return
     *     returns com.microsoft.sharepoint.webservices.DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult
     */
    @WebMethod(operationName = "DeleteContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentTypeXmlDocument")
    @WebResult(name = "DeleteContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "DeleteContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteContentTypeXmlDocument")
    @ResponseWrapper(localName = "DeleteContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.DeleteContentTypeXmlDocumentResponse")
    public com.microsoft.schemas.sharepoint.DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult deleteContentTypeXmlDocument(
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "documentUri", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String documentUri);

    /**
     * 
     * @param webUrl
     * @param listName
     * @param contentTypeId
     * @return
     *     returns com.microsoft.sharepoint.webservices.ApplyContentTypeToListResponse.ApplyContentTypeToListResult
     */
    @WebMethod(operationName = "ApplyContentTypeToList", action = "http://schemas.microsoft.com/sharepoint/soap/ApplyContentTypeToList")
    @WebResult(name = "ApplyContentTypeToListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    @RequestWrapper(localName = "ApplyContentTypeToList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.ApplyContentTypeToList")
    @ResponseWrapper(localName = "ApplyContentTypeToListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "com.microsoft.sharepoint.webservices.ApplyContentTypeToListResponse")
    public com.microsoft.schemas.sharepoint.ApplyContentTypeToListResponse.ApplyContentTypeToListResult applyContentTypeToList(
        @WebParam(name = "webUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String webUrl,
        @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String contentTypeId,
        @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
        String listName);

}
