
package com.microsoft.schemas.sharepoint;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Copy", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", wsdlLocation = "file:/C:/temp/audit/gen/Copy.wsdl")
public class Copy
    extends Service
{

    private final static URL COPY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.microsoft.schemas.sharepoint.Copy.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.microsoft.schemas.sharepoint.Copy.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/temp/audit/gen/Copy.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/temp/audit/gen/Copy.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COPY_WSDL_LOCATION = url;
    }

    public Copy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Copy() {
        super(COPY_WSDL_LOCATION, new QName("http://schemas.microsoft.com/sharepoint/soap/", "Copy"));
    }

    /**
     * 
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap")
    public CopySoap getCopySoap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap"), CopySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap")
    public CopySoap getCopySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap"), CopySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap12")
    public CopySoap getCopySoap12() {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap12"), CopySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CopySoap
     */
    @WebEndpoint(name = "CopySoap12")
    public CopySoap getCopySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sharepoint/soap/", "CopySoap12"), CopySoap.class, features);
    }

}
